# Prefix: 
# data_dir: GWAK_DATA_DIR
# container_root: GWAK_CONTAINER_ROOT
# output_dir: GWAK_OUTPUT_DIR
# export_dir: GWAK_TRITON_DIR

project: bbh

clean: False
batch_size: 10
kernel_size: 200
num_ifos: 2
gwak_instances: 1
platform: TENSORRT #TORCHSCRIPT


